const aws = 
	[{
		"text": "i/aws/Storage.png\"",
		"displayText": "Storage|AWS",
		"filename": "Storage"
	}, {
		"text": "i/aws/Security-Identity-Compliance.png\"",
		"displayText": "Security-Identity-Compliance|AWS",
		"filename": "Security-Identity-Compliance"
	}, {
		"text": "i/aws/Satellite.png\"",
		"displayText": "Satellite|AWS",
		"filename": "Satellite"
	}, {
		"text": "i/aws/Robotics.png\"",
		"displayText": "Robotics|AWS",
		"filename": "Robotics"
	}, {
		"text": "i/aws/Quantum-Technologies.png\"",
		"displayText": "Quantum-Technologies|AWS",
		"filename": "Quantum-Technologies"
	}, {
		"text": "i/aws/Networking-Content-Delivery.png\"",
		"displayText": "Networking-Content-Delivery|AWS",
		"filename": "Networking-Content-Delivery"
	}, {
		"text": "i/aws/Mobile.png\"",
		"displayText": "Mobile|AWS",
		"filename": "Mobile"
	}, {
		"text": "i/aws/Migration-Transfer.png\"",
		"displayText": "Migration-Transfer|AWS",
		"filename": "Migration-Transfer"
	}, {
		"text": "i/aws/Media-Services.png\"",
		"displayText": "Media-Services|AWS",
		"filename": "Media-Services"
	}, {
		"text": "i/aws/Management-Governance.png\"",
		"displayText": "Management-Governance|AWS",
		"filename": "Management-Governance"
	}, {
		"text": "i/aws/Machine-Learning.png\"",
		"displayText": "Machine-Learning|AWS",
		"filename": "Machine-Learning"
	}, {
		"text": "i/aws/IoT.png\"",
		"displayText": "IoT|AWS",
		"filename": "IoT"
	}, {
		"text": "i/aws/Game-Tech.png\"",
		"displayText": "Game-Tech|AWS",
		"filename": "Game-Tech"
	}, {
		"text": "i/aws/End-User-Computing.png\"",
		"displayText": "End-User-Computing|AWS",
		"filename": "End-User-Computing"
	}, {
		"text": "i/aws/Dev-Tools.png\"",
		"displayText": "Dev-Tools|AWS",
		"filename": "Dev-Tools"
	}, {
		"text": "i/aws/Database.png\"",
		"displayText": "Database|AWS",
		"filename": "Database"
	}, {
		"text": "i/aws/Customer-Engagement.png\"",
		"displayText": "Customer-Engagement|AWS",
		"filename": "Customer-Engagement"
	}, {
		"text": "i/aws/Customer-Enablement.png\"",
		"displayText": "Customer-Enablement|AWS",
		"filename": "Customer-Enablement"
	}, {
		"text": "i/aws/Cost-Management.png\"",
		"displayText": "Cost-Management|AWS",
		"filename": "Cost-Management"
	}, {
		"text": "i/aws/Containers.png\"",
		"displayText": "Containers|AWS",
		"filename": "Containers"
	}, {
		"text": "i/aws/Compute.png\"",
		"displayText": "Compute|AWS",
		"filename": "Compute"
	}, {
		"text": "i/aws/Business-Application.png\"",
		"displayText": "Business-Application|AWS",
		"filename": "Business-Application"
	}, {
		"text": "i/aws/Blockchain.png\"",
		"displayText": "Blockchain|AWS",
		"filename": "Blockchain"
	}, {
		"text": "i/aws/Application-Integration.png\"",
		"displayText": "Application-Integration|AWS",
		"filename": "Application-Integration"
	}, {
		"text": "i/aws/Analytics.png\"",
		"displayText": "Analytics|AWS",
		"filename": "Analytics"
	}, {
		"text": "i/aws/All-Products.png\"",
		"displayText": "All-Products|AWS",
		"filename": "All-Products"
	}, {
		"text": "i/aws/AR-VR.png\"",
		"displayText": "AR-VR|AWS",
		"filename": "AR-VR"
	}, {
		"text": "i/aws/Amazon-Redshift.png\"",
		"displayText": "Amazon-Redshift|AWS",
		"filename": "Amazon-Redshift"
	}, {
		"text": "i/aws/Amazon-QuickSight.png\"",
		"displayText": "Amazon-QuickSight|AWS",
		"filename": "Amazon-QuickSight"
	}, {
		"text": "i/aws/Amazon-Managed-Streaming-for-Apache-Kafka.png\"",
		"displayText": "Amazon-Managed-Streaming-for-Apache-Kafka|AWS",
		"filename": "Amazon-Managed-Streaming-for-Apache-Kafka"
	}, {
		"text": "i/aws/Amazon-Kinesis.png\"",
		"displayText": "Amazon-Kinesis|AWS",
		"filename": "Amazon-Kinesis"
	}, {
		"text": "i/aws/Amazon-Kinesis-Video-Streams",
		"displayText": "Amazon-Kinesis-Video-Streams|AWS",
		"filename": "Amazon-Kinesis-Video-Streams"
	}, {
		"text": "i/aws/Amazon-Kinesis-Firehose.png\"",
		"displayText": "Amazon-Kinesis-Firehose|AWS",
		"filename": "Amazon-Kinesis-Firehose"
	}, {
		"text": "i/aws/Amazon-Kinesis-Data-Streams.png\"",
		"displayText": "Amazon-Kinesis-Data-Streams|AWS",
		"filename": "Amazon-Kinesis-Data-Streams"
	}, {
		"text": "i/aws/Amazon-Kinesis-Data-Analytics.png\"",
		"displayText": "Amazon-Kinesis-Data-Analytics|AWS",
		"filename": "Amazon-Kinesis-Data-Analytics"
	}, {
		"text": "i/aws/Amazon-Elasticsearch-Service.png\"",
		"displayText": "Amazon-Elasticsearch-Service|AWS",
		"filename": "Amazon-Elasticsearch-Service"
	}, {
		"text": "i/aws/Amazon-EMR.png\"",
		"displayText": "Amazon-EMR|AWS",
		"filename": "Amazon-EMR"
	}, {
		"text": "i/aws/Amazon-CloudSearch.png\"",
		"displayText": "Amazon-CloudSearch|AWS",
		"filename": "Amazon-CloudSearch"
	}, {
		"text": "i/aws/Amazon-Athena.png\"",
		"displayText": "Amazon-Athena|AWS",
		"filename": "Amazon-Athena"
	}, {
		"text": "i/aws/AWS-Lake-Formation.png\"",
		"displayText": "AWS-Lake-Formation|AWS",
		"filename": "AWS-Lake-Formation"
	}, {
		"text": "i/aws/AWS-Glue.png\"",
		"displayText": "AWS-Glue|AWS",
		"filename": "AWS-Glue"
	}, {
		"text": "i/aws/AWS-Data-Pipeline.png\"",
		"displayText": "AWS-Data-Pipeline|AWS",
		"filename": "AWS-Data-Pipeline"
	}, {
		"text": "i/aws/Amazon-Simple-Queue-Service.png\"",
		"displayText": "Amazon-Simple-Queue-Service|AWS",
		"filename": "Amazon-Simple-Queue-Service"
	}, {
		"text": "i/aws/Amazon-Simple-Notification-Service.png\"",
		"displayText": "Amazon-Simple-Notification-Service|AWS",
		"filename": "Amazon-Simple-Notification-Service"
	}, {
		"text": "i/aws/AWS-Step-Functions.png\"",
		"displayText": "AWS-Step-Functions|AWS",
		"filename": "AWS-Step-Functions"
	}, {
		"text": "i/aws/AWS-Express-Workflows.png\"",
		"displayText": "AWS-Express-Workflows|AWS",
		"filename": "AWS-Express-Workflows"
	}, {
		"text": "i/aws/AWS-AppSync.png\"",
		"displayText": "AWS-AppSync|AWS",
		"filename": "AWS-AppSync"
	}, {
		"text": "i/aws/Amazon-MQ.png\"",
		"displayText": "Amazon-MQ|AWS",
		"filename": "Amazon-MQ"
	}, {
		"text": "i/aws/Amazon-EventBridge.png\"",
		"displayText": "Amazon-EventBridge|AWS",
		"filename": "Amazon-EventBridge"
	}, {
		"text": "i/aws/Amazon-Sumerian.png\"",
		"displayText": "Amazon-Sumerian|AWS",
		"filename": "Amazon-Sumerian"
	}, {
		"text": "i/aws/Amazon-Quantum-Ledger-Database",
		"displayText": "Amazon-Quantum-Ledger-Database|AWS",
		"filename": "Amazon-Quantum-Ledger-Database"
	}, {
		"text": "i/aws/Amazon-Managed-Blockchain.png\"",
		"displayText": "Amazon-Managed-Blockchain|AWS",
		"filename": "Amazon-Managed-Blockchain"
	}, {
		"text": "i/aws/Amazon-WorkMail.png\"",
		"displayText": "Amazon-WorkMail|AWS",
		"filename": "Amazon-WorkMail"
	}, {
		"text": "i/aws/Amazon-Chime.png\"",
		"displayText": "Amazon-Chime|AWS",
		"filename": "Amazon-Chime"
	}, {
		"text": "i/aws/Alexa-For-Business.png\"",
		"displayText": "Alexa-For-Business|AWS",
		"filename": "Alexa-For-Business"
	}, {
		"text": "i/aws/Amazon-Elastic-Kubernetes-Service.png\"",
		"displayText": "Amazon-Elastic-Kubernetes-Service|AWS",
		"filename": "Amazon-Elastic-Kubernetes-Service"
	}, {
		"text": "i/aws/Amazon-Elastic-Container-Service.png\"",
		"displayText": "Amazon-Elastic-Container-Service|AWS",
		"filename": "Amazon-Elastic-Container-Service"
	}, {
		"text": "i/aws/Amazon-Elastic-Container-Registry.png\"",
		"displayText": "Amazon-Elastic-Container-Registry|AWS",
		"filename": "Amazon-Elastic-Container-Registry"
	}, {
		"text": "i/aws/AWS-Fargate",
		"displayText": "AWS-Fargate|AWS",
		"filename": "AWS-Fargate"
	}, {
		"text": "i/aws/Bottlerocket.png\"",
		"displayText": "Bottlerocket|AWS",
		"filename": "Bottlerocket"
	}, {
		"text": "i/aws/Amazon-EC2-Image-Builder.png\"",
		"displayText": "Amazon-EC2-Image-Builder|AWS",
		"filename": "Amazon-EC2-Image-Builder"
	}, {
		"text": "i/aws/AWS-Wavelength.png\"",
		"displayText": "AWS-Wavelength|AWS",
		"filename": "AWS-Wavelength"
	}, {
		"text": "i/aws/AWS-Nitro-Enclaves.png\"",
		"displayText": "AWS-Nitro-Enclaves|AWS",
		"filename": "AWS-Nitro-Enclaves"
	}, {
		"text": "i/aws/AWS-Local-Zones.png\"",
		"displayText": "AWS-Local-Zones|AWS",
		"filename": "AWS-Local-Zones"
	}, {
		"text": "i/aws/AWS-Fargate.png\"",
		"displayText": "AWS-Fargate|AWS",
		"filename": "AWS-Fargate"
	}, {
		"text": "i/aws/VMware-Cloud-on-AWS.png\"",
		"displayText": "VMware-Cloud-on-AWS|AWS",
		"filename": "VMware-Cloud-on-AWS"
	}, {
		"text": "i/aws/Amazon-Lightsail.png\"",
		"displayText": "Amazon-Lightsail|AWS",
		"filename": "Amazon-Lightsail"
	}, {
		"text": "i/aws/Amazon-EC2.png\"",
		"displayText": "Amazon-EC2|AWS",
		"filename": "Amazon-EC2"
	}, {
		"text": "i/aws/Amazon-EC2-Auto-Scaling.png\"",
		"displayText": "Amazon-EC2-Auto-Scaling|AWS",
		"filename": "Amazon-EC2-Auto-Scaling"
	}, {
		"text": "i/aws/AWS-Serverless-Application-Repository.png\"",
		"displayText": "AWS-Serverless-Application-Repository|AWS",
		"filename": "AWS-Serverless-Application-Repository"
	}, {
		"text": "i/aws/AWS-Outposts.png\"",
		"displayText": "AWS-Outposts|AWS",
		"filename": "AWS-Outposts"
	}, {
		"text": "i/aws/AWS-Lambda.png\"",
		"displayText": "AWS-Lambda|AWS",
		"filename": "AWS-Lambda"
	}, {
		"text": "i/aws/AWS-Elastic-Beanstalk.png\"",
		"displayText": "AWS-Elastic-Beanstalk|AWS",
		"filename": "AWS-Elastic-Beanstalk"
	}, {
		"text": "i/aws/AWS-Batch.png\"",
		"displayText": "AWS-Batch|AWS",
		"filename": "AWS-Batch"
	}, {
		"text": "i/aws/Reserved-Instance-Reporting.png\"",
		"displayText": "Reserved-Instance-Reporting|AWS",
		"filename": "Reserved-Instance-Reporting"
	}, {
		"text": "i/aws/AWS-Cost-and-Usage-Report.png\"",
		"displayText": "AWS-Cost-and-Usage-Report|AWS",
		"filename": "AWS-Cost-and-Usage-Report"
	}, {
		"text": "i/aws/AWS-Cost-Explorer.png\"",
		"displayText": "AWS-Cost-Explorer|AWS",
		"filename": "AWS-Cost-Explorer"
	}, {
		"text": "i/aws/AWS-Budgets.png\"",
		"displayText": "AWS-Budgets|AWS",
		"filename": "AWS-Budgets"
	}, {
		"text": "i/aws/AWS-Training-Certification.png\"",
		"displayText": "AWS-Training-Certification|AWS",
		"filename": "AWS-Training-Certification"
	}, {
		"text": "i/aws/AWS-Support.png\"",
		"displayText": "AWS-Support|AWS",
		"filename": "AWS-Support"
	}, {
		"text": "i/aws/AWS-Managed-Services.png\"",
		"displayText": "AWS-Managed-Services|AWS",
		"filename": "AWS-Managed-Services"
	}, {
		"text": "i/aws/Amazon-Timestream.png\"",
		"displayText": "Amazon-Timestream|AWS",
		"filename": "Amazon-Timestream"
	}, {
		"text": "i/aws/Amazon-RDS.png\"",
		"displayText": "Amazon-RDS|AWS",
		"filename": "Amazon-RDS"
	}, {
		"text": "i/aws/Amazon-RDS-on-VMware.png\"",
		"displayText": "Amazon-RDS-on-VMware|AWS",
		"filename": "Amazon-RDS-on-VMware"
	}, {
		"text": "i/aws/Amazon-Quantum-Ledger-Database.png\"",
		"displayText": "Amazon-Quantum-Ledger-Database|AWS",
		"filename": "Amazon-Quantum-Ledger-Database"
	}, {
		"text": "i/aws/Amazon-Neptune.png\"",
		"displayText": "Amazon-Neptune|AWS",
		"filename": "Amazon-Neptune"
	}, {
		"text": "i/aws/Amazon-ElastiCache.png\"",
		"displayText": "Amazon-ElastiCache|AWS",
		"filename": "Amazon-ElastiCache"
	}, {
		"text": "i/aws/Amazon-DynamoDB.png\"",
		"displayText": "Amazon-DynamoDB|AWS",
		"filename": "Amazon-DynamoDB"
	}, {
		"text": "i/aws/Amazon-DocumentDB.png\"",
		"displayText": "Amazon-DocumentDB|AWS",
		"filename": "Amazon-DocumentDB"
	}, {
		"text": "i/aws/Amazon-Aurora.png\"",
		"displayText": "Amazon-Aurora|AWS",
		"filename": "Amazon-Aurora"
	}, {
		"text": "i/aws/AWS-Database-Migration-Service.png\"",
		"displayText": "AWS-Database-Migration-Service|AWS",
		"filename": "AWS-Database-Migration-Service"
	}, {
		"text": "i/aws/AWS-X-Ray.png\"",
		"displayText": "AWS-X-Ray|AWS",
		"filename": "AWS-X-Ray"
	}, {
		"text": "i/aws/AWS-Tools-and-SDKs.png\"",
		"displayText": "AWS-Tools-and-SDKs|AWS",
		"filename": "AWS-Tools-and-SDKs"
	}, {
		"text": "i/aws/AWS-Command-Line-Interface.png\"",
		"displayText": "AWS-Command-Line-Interface|AWS",
		"filename": "AWS-Command-Line-Interface"
	}, {
		"text": "i/aws/AWS-CodeStar.png\"",
		"displayText": "AWS-CodeStar|AWS",
		"filename": "AWS-CodeStar"
	}, {
		"text": "i/aws/AWS-CodePipeline.png\"",
		"displayText": "AWS-CodePipeline|AWS",
		"filename": "AWS-CodePipeline"
	}, {
		"text": "i/aws/AWS-CodeDeploy.png\"",
		"displayText": "AWS-CodeDeploy|AWS",
		"filename": "AWS-CodeDeploy"
	}, {
		"text": "i/aws/AWS-CodeCommit.png\"",
		"displayText": "AWS-CodeCommit|AWS",
		"filename": "AWS-CodeCommit"
	}, {
		"text": "i/aws/AWS-CodeBuild.png\"",
		"displayText": "AWS-CodeBuild|AWS",
		"filename": "AWS-CodeBuild"
	}, {
		"text": "i/aws/AWS-Cloud9.png\"",
		"displayText": "AWS-Cloud9|AWS",
		"filename": "AWS-Cloud9"
	}, {
		"text": "i/aws/AWS-Cloud-Development-Kit.png\"",
		"displayText": "AWS-Cloud-Development-Kit|AWS",
		"filename": "AWS-Cloud-Development-Kit"
	}, {
		"text": "i/aws/Amazon-WorkSpaces.png\"",
		"displayText": "Amazon-WorkSpaces|AWS",
		"filename": "Amazon-WorkSpaces"
	}, {
		"text": "i/aws/Amazon-WorkLink.png\"",
		"displayText": "Amazon-WorkLink|AWS",
		"filename": "Amazon-WorkLink"
	}, {
		"text": "i/aws/Amazon-WorkDocs",
		"displayText": "Amazon-WorkDocs|AWS",
		"filename": "Amazon-WorkDocs"
	}, {
		"text": "i/aws/Amazon-AppStream.png\"",
		"displayText": "Amazon-AppStream|AWS",
		"filename": "Amazon-AppStream"
	}, {
		"text": "i/aws/FreeRTOS.png\"",
		"displayText": "FreeRTOS|AWS",
		"filename": "FreeRTOS"
	}, {
		"text": "i/aws/AWS-IoT-Things-Graph.png\"",
		"displayText": "AWS-IoT-Things-Graph|AWS",
		"filename": "AWS-IoT-Things-Graph"
	}, {
		"text": "i/aws/AWS-IoT-SiteWise.png\"",
		"displayText": "AWS-IoT-SiteWise|AWS",
		"filename": "AWS-IoT-SiteWise"
	}, {
		"text": "i/aws/AWS-IoT-Greengrass.png\"",
		"displayText": "AWS-IoT-Greengrass|AWS",
		"filename": "AWS-IoT-Greengrass"
	}, {
		"text": "i/aws/AWS-IoT-Events.png\"",
		"displayText": "AWS-IoT-Events|AWS",
		"filename": "AWS-IoT-Events"
	}, {
		"text": "i/aws/AWS-IoT-Device-Management.png\"",
		"displayText": "AWS-IoT-Device-Management|AWS",
		"filename": "AWS-IoT-Device-Management"
	}, {
		"text": "i/aws/AWS-IoT-Device-Defender.png\"",
		"displayText": "AWS-IoT-Device-Defender|AWS",
		"filename": "AWS-IoT-Device-Defender"
	}, {
		"text": "i/aws/AWS-IoT-Core.png\"",
		"displayText": "AWS-IoT-Core|AWS",
		"filename": "AWS-IoT-Core"
	}, {
		"text": "i/aws/AWS-IoT-Button.png\"",
		"displayText": "AWS-IoT-Button|AWS",
		"filename": "AWS-IoT-Button"
	}, {
		"text": "i/aws/AWS-IoT-Analytics.png\"",
		"displayText": "AWS-IoT-Analytics|AWS",
		"filename": "AWS-IoT-Analytics"
	}, {
		"text": "i/aws/AWS-IoT-1-Click.png\"",
		"displayText": "AWS-IoT-1-Click|AWS",
		"filename": "AWS-IoT-1-Click"
	}, {
		"text": "i/aws/TensorFlow-on-AWS.png\"",
		"displayText": "TensorFlow-on-AWS|AWS",
		"filename": "TensorFlow-on-AWS"
	}, {
		"text": "i/aws/Apache-MXNet-on-AWS.png\"",
		"displayText": "Apache-MXNet-on-AWS|AWS",
		"filename": "Apache-MXNet-on-AWS"
	}, {
		"text": "i/aws/Amazon-Translate.png\"",
		"displayText": "Amazon-Translate|AWS",
		"filename": "Amazon-Translate"
	}, {
		"text": "i/aws/Amazon-Transcribe.png\"",
		"displayText": "Amazon-Transcribe|AWS",
		"filename": "Amazon-Transcribe"
	}, {
		"text": "i/aws/Amazon-Textract.png\"",
		"displayText": "Amazon-Textract|AWS",
		"filename": "Amazon-Textract"
	}, {
		"text": "i/aws/Amazon-SageMaker.png\"",
		"displayText": "Amazon-SageMaker|AWS",
		"filename": "Amazon-SageMaker"
	}, {
		"text": "i/aws/Amazon-SageMaker-Ground-Truth.png\"",
		"displayText": "Amazon-SageMaker-Ground-Truth|AWS",
		"filename": "Amazon-SageMaker-Ground-Truth"
	}, {
		"text": "i/aws/Amazon-Rekognition.png\"",
		"displayText": "Amazon-Rekognition|AWS",
		"filename": "Amazon-Rekognition"
	}, {
		"text": "i/aws/Amazon-Polly.png\"",
		"displayText": "Amazon-Polly|AWS",
		"filename": "Amazon-Polly"
	}, {
		"text": "i/aws/Amazon-Personalize.png\"",
		"displayText": "Amazon-Personalize|AWS",
		"filename": "Amazon-Personalize"
	}, {
		"text": "i/aws/Amazon-Lex.png\"",
		"displayText": "Amazon-Lex|AWS",
		"filename": "Amazon-Lex"
	}, {
		"text": "i/aws/Amazon-Kendra.png\"",
		"displayText": "Amazon-Kendra|AWS",
		"filename": "Amazon-Kendra"
	}, {
		"text": "i/aws/Amazon-Fraud-Detector.png\"",
		"displayText": "Amazon-Fraud-Detector|AWS",
		"filename": "Amazon-Fraud-Detector"
	}, {
		"text": "i/aws/Amazon-Forecast.png\"",
		"displayText": "Amazon-Forecast|AWS",
		"filename": "Amazon-Forecast"
	}, {
		"text": "i/aws/Amazon-Elastic-Inference.png\"",
		"displayText": "Amazon-Elastic-Inference|AWS",
		"filename": "Amazon-Elastic-Inference"
	}, {
		"text": "i/aws/Amazon-Comprehend.png\"",
		"displayText": "Amazon-Comprehend|AWS",
		"filename": "Amazon-Comprehend"
	}, {
		"text": "i/aws/Amazon-CodeGuru.png\"",
		"displayText": "Amazon-CodeGuru|AWS",
		"filename": "Amazon-CodeGuru"
	}, {
		"text": "i/aws/Amazon-Augmented-AI-A2I.png\"",
		"displayText": "Amazon-Augmented-AI-A2I|AWS",
		"filename": "Amazon-Augmented-AI-A2I"
	}, {
		"text": "i/aws/AWS-Neuron.png\"",
		"displayText": "AWS-Neuron|AWS",
		"filename": "AWS-Neuron"
	}, {
		"text": "i/aws/AWS-DeepRacer.png\"",
		"displayText": "AWS-DeepRacer|AWS",
		"filename": "AWS-DeepRacer"
	}, {
		"text": "i/aws/AWS-DeepLens.png\"",
		"displayText": "AWS-DeepLens|AWS",
		"filename": "AWS-DeepLens"
	}, {
		"text": "i/aws/AWS-DeepComposer.png\"",
		"displayText": "AWS-DeepComposer|AWS",
		"filename": "AWS-DeepComposer"
	}, {
		"text": "i/aws/AWS-Deep-Learning-Containers.png\"",
		"displayText": "AWS-Deep-Learning-Containers|AWS",
		"filename": "AWS-Deep-Learning-Containers"
	}, {
		"text": "i/aws/Amazon-CloudWatch.png\"",
		"displayText": "Amazon-CloudWatch|AWS",
		"filename": "Amazon-CloudWatch"
	}, {
		"text": "i/aws/AWS-Well-Architected-Tool.png\"",
		"displayText": "AWS-Well-Architected-Tool|AWS",
		"filename": "AWS-Well-Architected-Tool"
	}, {
		"text": "i/aws/AWS-Trusted-Advisor.png\"",
		"displayText": "AWS-Trusted-Advisor|AWS",
		"filename": "AWS-Trusted-Advisor"
	}, {
		"text": "i/aws/AWS-Systems-Manager.png\"",
		"displayText": "AWS-Systems-Manager|AWS",
		"filename": "AWS-Systems-Manager"
	}, {
		"text": "i/aws/AWS-Service-Catalog.png\"",
		"displayText": "AWS-Service-Catalog|AWS",
		"filename": "AWS-Service-Catalog"
	}, {
		"text": "i/aws/AWS-Personal-Health-Dashboard.png\"",
		"displayText": "AWS-Personal-Health-Dashboard|AWS",
		"filename": "AWS-Personal-Health-Dashboard"
	}, {
		"text": "i/aws/AWS-Organizations.png\"",
		"displayText": "AWS-Organizations|AWS",
		"filename": "AWS-Organizations"
	}, {
		"text": "i/aws/AWS-OpsWorks.png\"",
		"displayText": "AWS-OpsWorks|AWS",
		"filename": "AWS-OpsWorks"
	}, {
		"text": "i/aws/AWS-Management-Console.png\"",
		"displayText": "AWS-Management-Console|AWS",
		"filename": "AWS-Management-Console"
	}, {
		"text": "i/aws/AWS-License-Manager.png\"",
		"displayText": "AWS-License-Manager|AWS",
		"filename": "AWS-License-Manager"
	}, {
		"text": "i/aws/AWS-Launch-Wizard.png\"",
		"displayText": "AWS-Launch-Wizard|AWS",
		"filename": "AWS-Launch-Wizard"
	}, {
		"text": "i/aws/AWS-Control-Tower.png\"",
		"displayText": "AWS-Control-Tower|AWS",
		"filename": "AWS-Control-Tower"
	}, {
		"text": "i/aws/AWS-Config.png\"",
		"displayText": "AWS-Config|AWS",
		"filename": "AWS-Config"
	}, {
		"text": "i/aws/AWS-CloudTrail.png\"",
		"displayText": "AWS-CloudTrail|AWS",
		"filename": "AWS-CloudTrail"
	}, {
		"text": "i/aws/AWS-CloudFormation.png\"",
		"displayText": "AWS-CloudFormation|AWS",
		"filename": "AWS-CloudFormation"
	}, {
		"text": "i/aws/AWS-Auto-Scaling.png\"",
		"displayText": "AWS-Auto-Scaling|AWS",
		"filename": "AWS-Auto-Scaling"
	}, {
		"text": "i/aws/AWS-AppConfig.png\"",
		"displayText": "AWS-AppConfig|AWS",
		"filename": "AWS-AppConfig"
	}, {
		"text": "i/aws/Amazon-Kinesis-Video-Streams.png\"",
		"displayText": "Amazon-Kinesis-Video-Streams|AWS",
		"filename": "Amazon-Kinesis-Video-Streams"
	}, {
		"text": "i/aws/Amazon-Elastic-Transcoder.png\"",
		"displayText": "Amazon-Elastic-Transcoder|AWS",
		"filename": "Amazon-Elastic-Transcoder"
	}, {
		"text": "i/aws/AWS-Elemental-MediaTailor.png\"",
		"displayText": "AWS-Elemental-MediaTailor|AWS",
		"filename": "AWS-Elemental-MediaTailor"
	}, {
		"text": "i/aws/AWS-Elemental-MediaStore.png\"",
		"displayText": "AWS-Elemental-MediaStore|AWS",
		"filename": "AWS-Elemental-MediaStore"
	}, {
		"text": "i/aws/AWS-Elemental-MediaPackage.png\"",
		"displayText": "AWS-Elemental-MediaPackage|AWS",
		"filename": "AWS-Elemental-MediaPackage"
	}, {
		"text": "i/aws/AWS-Elemental-MediaLive.png\"",
		"displayText": "AWS-Elemental-MediaLive|AWS",
		"filename": "AWS-Elemental-MediaLive"
	}, {
		"text": "i/aws/AWS-Elemental-MediaConvert.png\"",
		"displayText": "AWS-Elemental-MediaConvert|AWS",
		"filename": "AWS-Elemental-MediaConvert"
	}, {
		"text": "i/aws/AWS-Elemental-MediaConnect.png\"",
		"displayText": "AWS-Elemental-MediaConnect|AWS",
		"filename": "AWS-Elemental-MediaConnect"
	}, {
		"text": "i/aws/AWS-Elemental-Appliances-&-Software.png\"",
		"displayText": "AWS-Elemental-Appliances-&-Software|AWS",
		"filename": "AWS-Elemental-Appliances-&-Software"
	}, {
		"text": "i/aws/CloudEndure-Migration.png\"",
		"displayText": "CloudEndure-Migration|AWS",
		"filename": "CloudEndure-Migration"
	}, {
		"text": "i/aws/AWS-Transfer-Family.png\"",
		"displayText": "AWS-Transfer-Family|AWS",
		"filename": "AWS-Transfer-Family"
	}, {
		"text": "i/aws/AWS-Server-Migration-Service.png\"",
		"displayText": "AWS-Server-Migration-Service|AWS",
		"filename": "AWS-Server-Migration-Service"
	}, {
		"text": "i/aws/AWS-Migration-Hub.png\"",
		"displayText": "AWS-Migration-Hub|AWS",
		"filename": "AWS-Migration-Hub"
	}, {
		"text": "i/aws/AWS-DataSync.png\"",
		"displayText": "AWS-DataSync|AWS",
		"filename": "AWS-DataSync"
	}, {
		"text": "i/aws/AWS-Application-Discovery-Service.png\"",
		"displayText": "AWS-Application-Discovery-Service|AWS",
		"filename": "AWS-Application-Discovery-Service"
	}, {
		"text": "i/aws/AWS-Device-Farm.png\"",
		"displayText": "AWS-Device-Farm|AWS",
		"filename": "AWS-Device-Farm"
	}, {
		"text": "i/aws/AWS-Amplify.png\"",
		"displayText": "AWS-Amplify|AWS",
		"filename": "AWS-Amplify"
	}, {
		"text": "i/aws/Elastic-Load-Balancing.png\"",
		"displayText": "Elastic-Load-Balancing|AWS",
		"filename": "Elastic-Load-Balancing"
	}, {
		"text": "i/aws/Amazon-Virtual-Private-Cloud.png\"",
		"displayText": "Amazon-Virtual-Private-Cloud|AWS",
		"filename": "Amazon-Virtual-Private-Cloud"
	}, {
		"text": "i/aws/Amazon-Route-53.png\"",
		"displayText": "Amazon-Route-53|AWS",
		"filename": "Amazon-Route-53"
	}, {
		"text": "i/aws/Amazon-CloudFront.png\"",
		"displayText": "Amazon-CloudFront|AWS",
		"filename": "Amazon-CloudFront"
	}, {
		"text": "i/aws/Amazon-Cloud-Directory.png\"",
		"displayText": "Amazon-Cloud-Directory|AWS",
		"filename": "Amazon-Cloud-Directory"
	}, {
		"text": "i/aws/AWS-Transit-Gateway.png\"",
		"displayText": "AWS-Transit-Gateway|AWS",
		"filename": "AWS-Transit-Gateway"
	}, {
		"text": "i/aws/AWS-PrivateLink.png\"",
		"displayText": "AWS-PrivateLink|AWS",
		"filename": "AWS-PrivateLink"
	}, {
		"text": "i/aws/AWS-Global-Accelerator.png\"",
		"displayText": "AWS-Global-Accelerator|AWS",
		"filename": "AWS-Global-Accelerator"
	}, {
		"text": "i/aws/AWS-Direct-Connect.png\"",
		"displayText": "AWS-Direct-Connect|AWS",
		"filename": "AWS-Direct-Connect"
	}, {
		"text": "i/aws/AWS-Cloud-Map.png\"",
		"displayText": "AWS-Cloud-Map|AWS",
		"filename": "AWS-Cloud-Map"
	}, {
		"text": "i/aws/AWS-Client-VPN.png\"",
		"displayText": "AWS-Client-VPN|AWS",
		"filename": "AWS-Client-VPN"
	}, {
		"text": "i/aws/AWS-App-Mesh.png\"",
		"displayText": "AWS-App-Mesh|AWS",
		"filename": "AWS-App-Mesh"
	}, {
		"text": "i/aws/AWS-RoboMaker.png\"",
		"displayText": "AWS-RoboMaker|AWS",
		"filename": "AWS-RoboMaker"
	}, {
		"text": "i/aws/AWS-Ground-Station.png\"",
		"displayText": "AWS-Ground-Station|AWS",
		"filename": "AWS-Ground-Station"
	}, {
		"text": "i/aws/Amazon-Macie.png\"",
		"displayText": "Amazon-Macie|AWS",
		"filename": "Amazon-Macie"
	}, {
		"text": "i/aws/Amazon-Inspector.png\"",
		"displayText": "Amazon-Inspector|AWS",
		"filename": "Amazon-Inspector"
	}, {
		"text": "i/aws/Amazon-GuardDuty.png\"",
		"displayText": "Amazon-GuardDuty|AWS",
		"filename": "Amazon-GuardDuty"
	}, {
		"text": "i/aws/Amazon-Detective.png\"",
		"displayText": "Amazon-Detective|AWS",
		"filename": "Amazon-Detective"
	}, {
		"text": "i/aws/Amazon-Cognito.png\"",
		"displayText": "Amazon-Cognito|AWS",
		"filename": "Amazon-Cognito"
	}, {
		"text": "i/aws/AWS-Single-Sign-On.png\"",
		"displayText": "AWS-Single-Sign-On|AWS",
		"filename": "AWS-Single-Sign-On"
	}, {
		"text": "i/aws/AWS-Shield.png\"",
		"displayText": "AWS-Shield|AWS",
		"filename": "AWS-Shield"
	}, {
		"text": "i/aws/AWS-Security-Hub.png\"",
		"displayText": "AWS-Security-Hub|AWS",
		"filename": "AWS-Security-Hub"
	}, {
		"text": "i/aws/AWS-Secrets-Manager.png\"",
		"displayText": "AWS-Secrets-Manager|AWS",
		"filename": "AWS-Secrets-Manager"
	}, {
		"text": "i/aws/AWS-Resource-Access-Manager.png\"",
		"displayText": "AWS-Resource-Access-Manager|AWS",
		"filename": "AWS-Resource-Access-Manager"
	}, {
		"text": "i/aws/AWS-Key-Management-Service.png\"",
		"displayText": "AWS-Key-Management-Service|AWS",
		"filename": "AWS-Key-Management-Service"
	}, {
		"text": "i/aws/AWS-Firewall-Manager.png\"",
		"displayText": "AWS-Firewall-Manager|AWS",
		"filename": "AWS-Firewall-Manager"
	}, {
		"text": "i/aws/AWS-Directory-Service.png\"",
		"displayText": "AWS-Directory-Service|AWS",
		"filename": "AWS-Directory-Service"
	}, {
		"text": "i/aws/AWS-CloudHSM.png\"",
		"displayText": "AWS-CloudHSM|AWS",
		"filename": "AWS-CloudHSM"
	}, {
		"text": "i/aws/AWS-Certificate-Manager.png\"",
		"displayText": "AWS-Certificate-Manager|AWS",
		"filename": "AWS-Certificate-Manager"
	}, {
		"text": "i/aws/AWS-Artifact.png\"",
		"displayText": "AWS-Artifact|AWS",
		"filename": "AWS-Artifact"
	}, {
		"text": "i/aws/AWS-Identity-and-Access-Management.png\"",
		"displayText": "AWS-Identity-and-Access-Management|AWS",
		"filename": "AWS-Identity-and-Access-Management"
	}, {
		"text": "i/aws/CloudEndure-Disaster-Recovery.png\"",
		"displayText": "CloudEndure-Disaster-Recovery|AWS",
		"filename": "CloudEndure-Disaster-Recovery"
	}, {
		"text": "i/aws/Amazon-FSx-for-Windows-File-Server.png\"",
		"displayText": "Amazon-FSx-for-Windows-File-Server|AWS",
		"filename": "Amazon-FSx-for-Windows-File-Server"
	}, {
		"text": "i/aws/Amazon-FSx-for-Lustre.png\"",
		"displayText": "Amazon-FSx-for-Lustre|AWS",
		"filename": "Amazon-FSx-for-Lustre"
	}, {
		"text": "i/aws/Amazon-Elastic-File-System.png\"",
		"displayText": "Amazon-Elastic-File-System|AWS",
		"filename": "Amazon-Elastic-File-System"
	}, {
		"text": "i/aws/Amazon-Elastic-Block-Store.png\"",
		"displayText": "Amazon-Elastic-Block-Store|AWS",
		"filename": "Amazon-Elastic-Block-Store"
	}, {
		"text": "i/aws/AWS-Storage-Gateway.png\"",
		"displayText": "AWS-Storage-Gateway|AWS",
		"filename": "AWS-Storage-Gateway"
	}, {
		"text": "i/aws/AWS-Snowmobile.png\"",
		"displayText": "AWS-Snowmobile|AWS",
		"filename": "AWS-Snowmobile"
	}, {
		"text": "i/aws/AWS-Snowball.png\"",
		"displayText": "AWS-Snowball|AWS",
		"filename": "AWS-Snowball"
	}, {
		"text": "i/aws/AWS-Snowball-Edge.png\"",
		"displayText": "AWS-Snowball-Edge|AWS",
		"filename": "AWS-Snowball-Edge"
	}, {
		"text": "i/aws/AWS-Backup.png\"",
		"displayText": "AWS-Backup|AWS",
		"filename": "AWS-Backup"
	}, {
		"text": "i/aws/Amazon-Braket.png\"",
		"displayText": "Amazon-Braket|AWS",
		"filename": "Amazon-Braket"
	}, {
		"text": "i/aws/AWS-Snowcone.png\"",
		"displayText": "AWS-Snowcone|AWS",
		"filename": "AWS-Snowcone"
	}, {
		"text": "i/aws/AWS-Console-Mobile-Application.png\"",
		"displayText": "AWS-Console-Mobile-Application|AWS",
		"filename": "AWS-Console-Mobile-Application"
	}, {
		"text": "i/aws/Savings-Plans.png\"",
		"displayText": "Savings-Plans|AWS",
		"filename": "Savings-Plans"
	}, {
		"text": "i/aws/Amazon-Application-Auto-Scaling.png\"",
		"displayText": "Amazon-Application-Auto-Scaling|AWS",
		"filename": "Amazon-Application-Auto-Scaling"
	}, {
		"text": "i/aws/AWS-ThinkBox-Deadline.png\"",
		"displayText": "AWS-ThinkBox-Deadline|AWS",
		"filename": "AWS-ThinkBox-Deadline"
	}, {
		"text": "i/aws/AWS-ThinkBox-XMesh.png\"",
		"displayText": "AWS-ThinkBox-XMesh|AWS",
		"filename": "AWS-ThinkBox-XMesh"
	}, {
		"text": "i/aws/AWS-ThinkBox-Frost.png\"",
		"displayText": "AWS-ThinkBox-Frost|AWS",
		"filename": "AWS-ThinkBox-Frost"
	}, {
		"text": "i/aws/AWS-ThinkBox-Krakatoa.png\"",
		"displayText": "AWS-ThinkBox-Krakatoa|AWS",
		"filename": "AWS-ThinkBox-Krakatoa"
	}, {
		"text": "i/aws/AWS-ThinkBox-Sequoia.png\"",
		"displayText": "AWS-ThinkBox-Sequoia|AWS",
		"filename": "AWS-ThinkBox-Sequoia"
	}, {
		"text": "i/aws/AWS-ThinkBox-Stoke.png\"",
		"displayText": "AWS-ThinkBox-Stoke|AWS",
		"filename": "AWS-ThinkBox-Stoke"
	}, {
		"text": "i/aws/AWS-Compute-Optimizer.png\"",
		"displayText": "AWS-Compute-Optimizer|AWS",
		"filename": "AWS-Compute-Optimizer"
	}, {
		"text": "i/aws/AWS-Site-to-Site-VPN.png\"",
		"displayText": "AWS-Site-to-Site-VPN|AWS",
		"filename": "AWS-Site-to-Site-VPN"
	}, {
		"text": "i/aws/AWS-Deep-Learning-AMIs.png\"",
		"displayText": "AWS-Deep-Learning-AMIs|AWS",
		"filename": "AWS-Deep-Learning-AMIs"
	}, {
		"text": "i/aws/Amazon-Keyspaces.png\"",
		"displayText": "Amazon-Keyspaces|AWS",
		"filename": "Amazon-Keyspaces"
	}, {
		"text": "i/aws/AWS-Professional-Services.png\"",
		"displayText": "AWS-Professional-Services|AWS",
		"filename": "AWS-Professional-Services"
	}, {
		"text": "i/aws/AWS-IQ.png\"",
		"displayText": "AWS-IQ|AWS",
		"filename": "AWS-IQ"
	}, {
		"text": "i/aws/Amazon-Cloud-Directory",
		"displayText": "Amazon-Cloud-Directory|AWS",
		"filename": "Amazon-Cloud-Directory"
	}, {
		"text": "i/aws/Amazon-FSx.png\"",
		"displayText": "Amazon-FSx|AWS",
		"filename": "Amazon-FSx"
	}, {
		"text": "i/aws/AWS-ParallelCluster.png\"",
		"displayText": "AWS-ParallelCluster|AWS",
		"filename": "AWS-ParallelCluster"
	}, {
		"text": "i/aws/Amazon-GameLift.png\"",
		"displayText": "Amazon-GameLift|AWS",
		"filename": "Amazon-GameLift"
	}, {
		"text": "i/aws/Amazon-Simple-Storage-Service-Glacier.png\"",
		"displayText": "Amazon-Simple-Storage-Service-Glacier|AWS",
		"filename": "Amazon-Simple-Storage-Service-Glacier"
	}, {
		"text": "i/aws/AWS-WAF.png\"",
		"displayText": "AWS-WAF|AWS",
		"filename": "AWS-WAF"
	}, {
		"text": "i/aws/AWS-CodeArtifact.png\"",
		"displayText": "AWS-CodeArtifact|AWS",
		"filename": "AWS-CodeArtifact"
	}, {
		"text": "i/aws/AWS-Chatbot.png\"",
		"displayText": "AWS-Chatbot|AWS",
		"filename": "AWS-Chatbot"
	}, {
		"text": "i/aws/AWS-Data-Exchange.png\"",
		"displayText": "AWS-Data-Exchange|AWS",
		"filename": "AWS-Data-Exchange"
	}, {
		"text": "i/aws/TorchServe.png\"",
		"displayText": "TorchServe|AWS",
		"filename": "TorchServe"
	}, {
		"text": "i/aws/AWS-Backint-Agent.png\"",
		"displayText": "AWS-Backint-Agent|AWS",
		"filename": "AWS-Backint-Agent"
	}, {
		"text": "i/aws/Serverless.png\"",
		"displayText": "Serverless|AWS",
		"filename": "Serverless"
	}, {
		"text": "i/aws/Amazon-Interactive-Video-Service.png\"",
		"displayText": "Amazon-Interactive-Video-Service|AWS",
		"filename": "Amazon-Interactive-Video-Service"
	}, {
		"text": "i/aws/AWS-Elemental-Link.png\"",
		"displayText": "AWS-Elemental-Link|AWS",
		"filename": "AWS-Elemental-Link"
	}, {
		"text": "i/aws/Amazon-Lumberyard.png\"",
		"displayText": "Amazon-Lumberyard|AWS",
		"filename": "Amazon-Lumberyard"
	}, {
		"text": "i/aws/AWS-Activate.png\"",
		"displayText": "AWS-Activate|AWS",
		"filename": "AWS-Activate"
	}, {
		"text": "i/aws/AWS-Signer.png\"",
		"displayText": "AWS-Signer|AWS",
		"filename": "AWS-Signer"
	}, {
		"text": "i/aws/Amazon-S3-On-Outposts_Storage.png\"",
		"displayText": "Amazon-S3-On-Outposts_Storage|AWS",
		"filename": "Amazon-S3-On-Outposts_Storage"
	}, {
		"text": "i/aws/AWS-Panorama.png\"",
		"displayText": "AWS-Panorama|AWS",
		"filename": "AWS-Panorama"
	}, {
		"text": "i/aws/AWS-Network-Firewall.png\"",
		"displayText": "AWS-Network-Firewall|AWS",
		"filename": "AWS-Network-Firewall"
	}, {
		"text": "i/aws/Amazon-Managed-Workflows-for-Apache-Airflow.png\"",
		"displayText": "Amazon-Managed-Workflows-for-Apache-Airflow|AWS",
		"filename": "Amazon-Managed-Workflows-for-Apache-Airflow"
	}, {
		"text": "i/aws/Amazon-Monitron.png\"",
		"displayText": "Amazon-Monitron|AWS",
		"filename": "Amazon-Monitron"
	}, {
		"text": "i/aws/Amazon-Lookout-for-Metrics.png\"",
		"displayText": "Amazon-Lookout-for-Metrics|AWS",
		"filename": "Amazon-Lookout-for-Metrics"
	}, {
		"text": "i/aws/Amazon-Lookout-for-Vision.png\"",
		"displayText": "Amazon-Lookout-for-Vision|AWS",
		"filename": "Amazon-Lookout-for-Vision"
	}, {
		"text": "i/aws/Red-Hat-OpenShift.png\"",
		"displayText": "Red-Hat-OpenShift|AWS",
		"filename": "Red-Hat-OpenShift"
	}, {
		"text": "i/aws/Amazon-Lookout-for-Equipment.png\"",
		"displayText": "Amazon-Lookout-for-Equipment|AWS",
		"filename": "Amazon-Lookout-for-Equipment"
	}, {
		"text": "i/aws/Amazon-Location-Service.png\"",
		"displayText": "Amazon-Location-Service|AWS",
		"filename": "Amazon-Location-Service"
	}, {
		"text": "i/aws/Amazon-HealthLake.png\"",
		"displayText": "Amazon-HealthLake|AWS",
		"filename": "Amazon-HealthLake"
	}, {
		"text": "i/aws/AWS-Proton.png\"",
		"displayText": "AWS-Proton|AWS",
		"filename": "AWS-Proton"
	}, {
		"text": "i/aws/AWS-SQL-Workbench.png\"",
		"displayText": "AWS-SQL-Workbench|AWS",
		"filename": "AWS-SQL-Workbench"
	}, {
		"text": "i/aws/Amazon-DevOps-Guru.png\"",
		"displayText": "Amazon-DevOps-Guru|AWS",
		"filename": "Amazon-DevOps-Guru"
	}, {
		"text": "i/aws/AWS-Outposts-1U-and-2U-Servers.png\"",
		"displayText": "AWS-Outposts-1U-and-2U-Servers|AWS",
		"filename": "AWS-Outposts-1U-and-2U-Servers"
	}, {
		"text": "i/aws/AWS-Fault-Injection-Simulator.png\"",
		"displayText": "AWS-Fault-Injection-Simulator|AWS",
		"filename": "AWS-Fault-Injection-Simulator"
	}, {
		"text": "i/aws/AWS-CloudShell.png\"",
		"displayText": "AWS-CloudShell|AWS",
		"filename": "AWS-CloudShell"
	}, {
		"text": "i/aws/Amazon-EKS-Anywhere.png\"",
		"displayText": "Amazon-EKS-Anywhere|AWS",
		"filename": "Amazon-EKS-Anywhere"
	}, {
		"text": "i/aws/Amazon-EKS-Distro.png\"",
		"displayText": "Amazon-EKS-Distro|AWS",
		"filename": "Amazon-EKS-Distro"
	}, {
		"text": "i/aws/Amazon-EKS-Cloud.png\"",
		"displayText": "Amazon-EKS-Cloud|AWS",
		"filename": "Amazon-EKS-Cloud"
	}, {
		"text": "i/aws/Amazon-Managed-Service-for-Grafana.png\"",
		"displayText": "Amazon-Managed-Service-for-Grafana|AWS",
		"filename": "Amazon-Managed-Service-for-Grafana"
	}, {
		"text": "i/aws/Amazon-Managed-Service-for-Prometheus.png\"",
		"displayText": "Amazon-Managed-Service-for-Prometheus|AWS",
		"filename": "Amazon-Managed-Service-for-Prometheus"
	}, {
		"text": "i/aws/AWS-Audit-Manager.png\"",
		"displayText": "AWS-Audit-Manager|AWS",
		"filename": "AWS-Audit-Manager"
	}, {
		"text": "i/aws/AWS-Glue-Elastic-Views.png\"",
		"displayText": "AWS-Glue-Elastic-Views|AWS",
		"filename": "AWS-Glue-Elastic-Views"
	}, {
		"text": "i/aws/Amazon-Honeycode.png\"",
		"displayText": "Amazon-Honeycode|AWS",
		"filename": "Amazon-Honeycode"
	}, {
		"text": "i/aws/AWS-Distro-for-OpenTelemetry.png\"",
		"displayText": "AWS-Distro-for-OpenTelemetry|AWS",
		"filename": "AWS-Distro-for-OpenTelemetry"
	}, {
		"text": "i/aws/AWS-Migration-Evaluator.png\"",
		"displayText": "AWS-Migration-Evaluator|AWS",
		"filename": "AWS-Migration-Evaluator"
	}, {
		"text": "i/aws/Amazon-AppFlow.png\"",
		"displayText": "Amazon-AppFlow|AWS",
		"filename": "Amazon-AppFlow"
	}, {
		"text": "i/aws/Amazon-API-Gateway.png\"",
		"displayText": "Amazon-API-Gateway|AWS",
		"filename": "Amazon-API-Gateway"
	}, {
		"text": "i/aws/AWS-Elemental-Server.png\"",
		"displayText": "AWS-Elemental-Server|AWS",
		"filename": "AWS-Elemental-Server"
	}, {
		"text": "i/aws/AWS-Elemental-Live.png\"",
		"displayText": "AWS-Elemental-Live|AWS",
		"filename": "AWS-Elemental-Live"
	}, {
		"text": "i/aws/AWS-Elemental-Delta.png\"",
		"displayText": "AWS-Elemental-Delta|AWS",
		"filename": "AWS-Elemental-Delta"
	}, {
		"text": "i/aws/AWS-Elemental-Conductor.png\"",
		"displayText": "AWS-Elemental-Conductor|AWS",
		"filename": "AWS-Elemental-Conductor"
	}, {
		"text": "i/aws/NICE-DCV.png\"",
		"displayText": "NICE-DCV|AWS",
		"filename": "NICE-DCV"
	}, {
		"text": "i/aws/Elastic-Fabric-Adapter.png\"",
		"displayText": "Elastic-Fabric-Adapter|AWS",
		"filename": "Elastic-Fabric-Adapter"
	}, {
		"text": "i/aws/Amazon-Simple-Storage-Service.png\"",
		"displayText": "Amazon-Simple-Storage-Service|AWS",
		"filename": "Amazon-Simple-Storage-Service"
	}, {
		"text": "i/aws/AWS-Application-Auto-Scaling.png\"",
		"displayText": "AWS-Application-Auto-Scaling|AWS",
		"filename": "AWS-Application-Auto-Scaling"
	}, {
		"text": "i/aws/AWS-Custom-Billing-Manager.png\"",
		"displayText": "AWS-Custom-Billing-Manager|AWS",
		"filename": "AWS-Custom-Billing-Manager"
	}, {
		"text": "i/aws/AWS-Glue-DataBrew.png\"",
		"displayText": "AWS-Glue-DataBrew|AWS",
		"filename": "AWS-Glue-DataBrew"
	}, {
		"text": "i/aws/Amazon-Simple-Email-Service.png\"",
		"displayText": "Amazon-Simple-Email-Service|AWS",
		"filename": "Amazon-Simple-Email-Service"
	}, {
		"text": "i/aws/Amazon-Pinpoint.png\"",
		"displayText": "Amazon-Pinpoint|AWS",
		"filename": "Amazon-Pinpoint"
	}, {
		"text": "i/aws/Amazon-Connect.png\"",
		"displayText": "Amazon-Connect|AWS",
		"filename": "Amazon-Connect"
	}, {
		"text": "i/aws/Amazon-WorkDocs.png\"",
		"displayText": "Amazon-WorkDocs|AWS",
		"filename": "Amazon-WorkDocs"
	}, {
		"text": "i/aws/Amazon-Corretto.png\"",
		"displayText": "Amazon-Corretto|AWS",
		"filename": "Amazon-Corretto"
	}, {
		"text": "i/aws/Amazon-WorkDocs-SDK.png\"",
		"displayText": "Amazon-WorkDocs-SDK|AWS",
		"filename": "Amazon-WorkDocs-SDK"
	}, {
		"text": "i/aws/Amazon-Pinpoint-APIs.png\"",
		"displayText": "Amazon-Pinpoint-APIs|AWS",
		"filename": "Amazon-Pinpoint-APIs"
	}, {
		"text": "i/aws/Amazon-Chime-Voice-Connector.png\"",
		"displayText": "Amazon-Chime-Voice-Connector|AWS",
		"filename": "Amazon-Chime-Voice-Connector"
	}, {
		"text": "i/aws/Amazon-Chime-SDK.png\"",
		"displayText": "Amazon-Chime-SDK|AWS",
		"filename": "Amazon-Chime-SDK"
	}, {
		"text": "i/aws/AWS-Marketplace_Light.png\"",
		"displayText": "AWS-Marketplace_Light|AWS",
		"filename": "AWS-Marketplace_Light"
	}, {
		"text": "i/aws/AWS-Marketplace_Dark.png\"",
		"displayText": "AWS-Marketplace_Dark|AWS",
		"filename": "AWS-Marketplace_Dark"
	}, {
		"text": "i/aws/foo.sh",
		"displayText": "foo|AWS",
		"filename": "foo"
	}]
